# This is a basic workflow to help you get started with Actions

name: DR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      switch_to_region:
        type: choice
        description: provide ur choice
        options: 
        - us-west
        - us-east

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  LB_REBASE_US_WEST:
    runs-on: ubuntu-latest
    if: contains(input.switch_to_region, "us-west")
    steps:
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: 'grand-thought-365806'
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: cp your-file.txt gs://your-bucket/
          cli: gcloud
      - name: run sample command
        run: gcloud compute instances list
  
