# This is a basic workflow to help you get started with Actions

name: DR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      switch_to_region:
        type: choice
        description: provide ur choice
        options: 
        - us-west
        - us-east

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  LB_REBASE_US_WEST:
    runs-on: ubuntu-latest
    if: contains(inputs.switch_to_region, 'us-west')
    env:
      PROJECT_ID: 'grand-thought-365806'
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_key: '$ {{ secrets.SERVICE_ACCOUNT_KEY }}'
          project_id: 'grand-thought-365806'
          install_components: gcloud
          export_default_credentials: true
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          gcloud version
          gcloud conpute instances list
  
