name: Cleanup_And_Restore

# Controls when the workflow will run
on:
  workflow_dispatch:


env:
      PROJECT_ID: 'grand-thought-365806'
      
      geodb_us-east: geodb
      notifydb_us-east: notifydb
      securitydb-dr_us-east: securitydb-dr
      serviceproviderdb-dr_us-east: serviceproviderdb-dr
      tresurydb-dr_us-east: tresurydb-dr
      workorderdb-dr_us-east: workorderdb-dr
      servicecatalogdb-dr_us-east: servicecatalogdb-dr
      
      geodb_us-west: geodb-replica
      notifydb_us-west: notifydb-replica
      securitydb-dr_us-west: securitydb-dr-replica
      serviceproviderdb-dr_us-west: serviceproviderdb-dr-replica
      tresurydb-dr_us-west: tresurydb-dr-replica
      workorderdb-dr_us-west: workorderdb-dr-replica
      servicecatalogdb-dr_us-west: servicecatalogdb-dr-replica
      
jobs:
  use_env:
    runs-on: ubuntu-latest
    steps:
      - name: "use env"
        run: |
          echo $geodb_us-west
          echo $servicecatalogdb-dr_us-east
