name: Cleanup_And_Restore

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      test:
        type: choice
        description: test
        options:
          - yes
          - no


      
jobs:
  use_env:
    runs-on: ubuntu-latest
    steps:
      - name: "use env"
        run: |
          if [ ${{ github.event.inputs.test }} ]
          then
            echo "you selecte true"
          else
            echo "you selected false"
          fi
          

